stages:
  - build
  - test
  - release
  - deploy

variables:
  DOCKER_IMAGE: $CI_REGISTRY_IMAGE:$CI_BUILD_REF_NAME
  DOCKER_IMAGE_ANSIBLE: registry.pieoneers.com/ips/ips-ansible:master
  DOCKER_LOGIN_USERNAME: gitlab-ci-token
  DOCKER_LOGIN_PASSWORD: $CI_BUILD_TOKEN

before_script:
  - docker login -u $DOCKER_LOGIN_USERNAME -p $DOCKER_LOGIN_PASSWORD $CI_REGISTRY

build:
  stage: build
  script:
    - docker build --build-arg ASSETS_PRECOMPILE=please -t ips-app .

test:
  stage: test
  script:
    - docker-compose -f docker-compose.yml -f docker-compose.ci.yml up -d db
    - docker-compose -f docker-compose.yml -f docker-compose.ci.yml run --rm wait_for
    - docker-compose -f docker-compose.yml -f docker-compose.ci.yml run --rm app rake db:setup
    - docker-compose -f docker-compose.yml -f docker-compose.ci.yml run --rm app test
  after_script:
    - docker-compose -f docker-compose.yml -f docker-compose.ci.yml down

release:
  stage: release
  script:
    - docker tag ips-app $DOCKER_IMAGE
    - docker push $DOCKER_IMAGE
  only:
    - develop
    - master

staging:
  stage: deploy
  environment: staging
  variables:
    SSH_PRIVATE_KEY: $SSH_PRIVATE_KEY_STAGING
  before_script:
    - docker login -u $DOCKER_LOGIN_USERNAME -p $DOCKER_LOGIN_PASSWORD $CI_REGISTRY
    - docker pull $DOCKER_IMAGE_ANSIBLE
  script: >
    docker run --rm
    --env SSH_PRIVATE_KEY="$SSH_PRIVATE_KEY"
    --env DO_API_TOKEN=$DO_API_TOKEN
    --env ANSIBLE_VAULT_PASSWORD=$ANSIBLE_VAULT_PASSWORD
    --env DOCKER_LOGIN_USERNAME=$DOCKER_LOGIN_USERNAME
    --env DOCKER_LOGIN_PASSWORD=$DOCKER_LOGIN_PASSWORD
    --env DOCKER_IMAGE=$DOCKER_IMAGE
    $DOCKER_IMAGE_ANSIBLE deploy:staging
  only:
    - develop

production:
  stage: deploy
  environment: production
  variables:
    SSH_PRIVATE_KEY: $SSH_PRIVATE_KEY_PRODUCTION
  before_script:
    - docker login -u $DOCKER_LOGIN_USERNAME -p $DOCKER_LOGIN_PASSWORD $CI_REGISTRY
    - docker pull $DOCKER_IMAGE_ANSIBLE
  script: >
    docker run --rm
    --env SSH_PRIVATE_KEY="$SSH_PRIVATE_KEY"
    --env DO_API_TOKEN=$DO_API_TOKEN
    --env ANSIBLE_VAULT_PASSWORD=$ANSIBLE_VAULT_PASSWORD
    --env DOCKER_LOGIN_USERNAME=$DOCKER_LOGIN_USERNAME
    --env DOCKER_LOGIN_PASSWORD=$DOCKER_LOGIN_PASSWORD
    --env DOCKER_IMAGE=$DOCKER_IMAGE
    $DOCKER_IMAGE_ANSIBLE deploy:production
  only:
    - master
  when: manual
