version: "2"

services:
  app:
    environment:
      DATABASE_URL: postgresql://postgres:@db/ips
      EMAIL_SENDER: ips@pieoneers.com
    volumes:
      - .:/app/user
    ports:
      - "80:80"

  db:
    ports:
      - "5432:5432"
