---
provinces:
  -
    name: "Alberta"
    abbr: "AB"
    gst: 0.05
    pst: 0.0
  -
    name: "British Columbia"
    abbr: "BC"
    gst: 0.05
    pst: 0.07
  -
    name: "Manitoba"
    abbr: "MB"
    gst: 0.05
    pst: 0.08
  -
    name: "New Brunswick"
    abbr: "NB"
    gst: 0.05
    pst: 0.08
  -
    name: "Newfoundland"
    abbr: "NL"
    gst: 0.05
    pst: 0.08
  -
    name: "Northwest Territories"
    abbr: "NT"
    gst: 0.05
    pst: 0.0
  -
    name: "Nova Scotia"
    abbr: "NS"
    gst: 0.05
    pst: 0.1
  -
    name: "Nunavut"
    abbr: "NU"
    gst: 0.05
    pst: 0.0
  -
    name: "Ontario"
    abbr: "ON"
    gst: 0.05
    pst: 0.08
  -
    name: "Prince Edward Island"
    abbr: "PE"
    gst: 0.05
    pst: 0.09
  -
    name: "Quebec"
    abbr: "QC"
    gst: 0.05
    pst: 0.09975
  -
    name: "Saskatchewan"
    abbr: "SK"
    gst: 0.05
    pst: 0.06
  -
    name: "Yukon Territory"
    abbr: "YT"
    gst: 0.05
    pst: 0.0
